### ISSUE TITLE
Release 1.2.0 depends on nightly channel

### ISSUE THREAD

**Issue by Youka** [asmoaesl/rsc#5]
Tried a very simple example in integration test:
`assert!(rsc::eval("5^2").unwrap() == 25.0);`

Got a compile error:
```
>cargo test
   Compiling rsc v1.2.0
error[E0554]: #![feature] may not be used on the stable release channel
  --> C:\Users\Youka\.cargo\registry\src\github.com-1ecc6299db9ec823\rsc-1.2.0\src/lib.rs:55:1
   |
55 | #![feature(test)]
   | ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `rsc`.
```

Seems this crate depends on standard benchmarking which is still not stable. Missing the note about this restriction in crate description.

**Comment by asmoaesl** [comment]
Thanks, I'll get on it!

**Comment by asmoaesl** [comment]
Fixed it! Don't forget to `cargo clean` before trying again. Thanks for telling me.

**Comment by Youka** [comment]
Works!
Thank you very much.

**Comment by asmoaesl** [comment]
And I'm gonna try to get v2.0 published on Cargo today, if I can get everything finished.
